---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekatzgmo/MyPortfolio/
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp node_module/* $DEPLOYPATH
    - /bin/cp static/* $DEPLOYPATH
    - /bin/cp templates/* $DEPLOYPATH
