---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekatzgmo/MyPortfolio/
    - /bin/cp app.py $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp -R node_module $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
