---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ekatzgmo/MyPortfolio/
    - cp app.py $DEPLOYPATH
    - cp package.json $DEPLOYPATH
    - cp package-lock.json $DEPLOYPATH
    - cp requirements.txt $DEPLOYPATH
    - cp -R node_modules $DEPLOYPATH
    - cp -R static $DEPLOYPATH
    - cp -R templates $DEPLOYPATH